#!/bin/bash
# Usage: sbatch slurm-gpu-job-script
# Prepared By: Kai Xi,  Feb 2015
#              help@massive.org.au

# Modified By : Isaac Ning Lee,  Dec 2023

# NOTE: To activate a SLURM option, remove the whitespace between the '#' and 'SBATCH'

# To give your job a name, replace "MyJob" with an appropriate name
#SBATCH --job-name=ilee_cp_cpsd_224_lucir_fm3_joint_cg

# Request CPU resource for a serial job
# SBATCH --ntasks=1
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=1

# Request for GPU, 
#
# Option 1: Choose any GPU whatever m2070 or K20
# Note in most cases, 'gpu:N' should match '--ntasks=N'
#SBATCH --gres=gpu:40gb:1
#SBATCH --partition=BigCats
#SBATCH --qos=Lion

#SBATCH --mem-per-cpu=60000

# Set the file for output (stdout)
#SBATCH --output=logs/cp_cpsd_224_lucir_fm3_joint_cg.out

# Set the file for error log (stderr)
#SBATCH --error=logs/cp_cpsd_224_lucir_fm3_joint_cg.err


# Command to run

nvidia-smi
source /mnt/userdata3/cl-gen/miniforge3/bin/activate
conda activate stable_diff
cd /mnt/userdata3/cl-gen/CPSD
bash run.sh